"""Fixed report-language strings shared by lab/auditor/api/report.py's HTML,
JSON, and PDF exports - authored text, never model output, same rule this
project already applies to policies/nca/compliance_text.py.
"""

METHODOLOGY = (
    "Findings are produced by policies/engine/policy_engine.py, a deterministic "
    "rule evaluator: each control's YAML-defined pass/fail/partial conditions are "
    "checked against structured observations from an automated collector "
    "(policies/catalog/scan_tests.py) or a manually recorded evidence record. No "
    "finding, status, or remediation text in this report is generated by an AI "
    "model - every value is either a stored database value or text copied "
    "verbatim from a control definition."
)

DISCLAIMER = (
    "This report reflects the result of automated and manual technical "
    "assessments against a small set of NCA CGIoT-1:2024-mapped controls. It is "
    "not an official certification and does not itself establish regulatory "
    "compliance."
)
