listener 8883
allow_anonymous false
password_file /mosquitto/config/passwd
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/mqtt-server.crt
keyfile /mosquitto/certs/mqtt-server.key
require_certificate false
persistence false
log_dest stdout
