name: kaust-iot-lab

networks:
  audit-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
  internal-network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.31.0.0/24

services: {}
